Pass style to default_url proc/method when able
This takes care not to pass it if we can't be certain the object is expecting
an extra parameter so that existing `lambda { |attachment| ...}` blocks don't
blow up a la:

    irb(main):001:0> lambda { |a| }.call(1, 2)
    ArgumentError: wrong number of arguments (2 for 1)
    	from (irb):1:in `block in irb_binding'
    	from (irb):1:in `call'
    	from (irb):1
    	from /Users/bjeanes/.rubies/ruby-2.1.5/bin/irb:11:in `<main>'